Überarbeitung Modul 0
isaqb-org/curriculum-data pull request #19
Opened 2024-05-14 09:13 UTC by ck-innoq

2024-05-14 09:41 UTC, RainerJaspert requested changes
Wir sollten die englische Version direkt anpassen oder auf TBD setzen.
Und wir können bei der Gelegenheit auch direkt die Zeitvorgaben überarbeiten.
Auch die weiteren Kapitel des Moduls 0 (Voraussetzungen, etc) würde ich hier direkt mit betrachten.

2024-05-16 09:04 UTC, ck-innoq commented
Die englische Version habe ich angepasst.

2024-05-27 06:23 UTC, ck-innoq commented
Zeitvorgaben sind ebenfalls überarbeitet

2024-06-04 13:08 UTC, RainerJaspert approved these changes

2024-06-04 13:08 UTC, merged